
import Footer from "@/components/footer/Footer";
import "./globals.css";
import Promotions from "@/components/promotions/Promotions";
import NavBar from "@/components/navbar/NavBar";
import TopBar from "@/components/navbar/TopBar";
import ReduxProvider from "@/redux/provider/ReduxProvider";
import HotToast from "@/shared/toast/HotToast";






export const metadata = {
  title: "Digital product services in bangladesh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <TopBar />
          <NavBar />
          {children}
          {/* Footer Here  */}
          <Promotions />
          <Footer />
          <HotToast />
        </ReduxProvider>
      </body>
    </html>
  );
}
