
import "./globals.css";
import TopBar from "@/components/Navbar/TopBar";
import Footer from "@/components/Footer/Footer";
import ReduxProvider from "@/redux/ReduxProvider/ReduxProvider";
import HotToast from "@/components/Toast/HotToast";
import TopJointBar from "@/components/Navbar/TopJointBar";
import MoblieBar from "@/components/Navbar/MoblieBar";
import Promotions from "@/components/Promotions/Promotions";
import NavBar from "@/components/Navbar/NavBar";







export const metadata = {
  title: "Digital product services in bangladesh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <TopJointBar />
          <MoblieBar />
          <TopBar />
          <NavBar />
          {children}
          {/* Footer Here  */}
          <Promotions />
          <Footer />
          <HotToast />
        </ReduxProvider>
      </body>
    </html>
  );
}
